# Generated by Django 4.2.6 on 2023-10-30 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_workerresume_employeerresume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerresume',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^(?:\\+7|8)\\d{10}$')]),
        ),
    ]
