# Generated by Django 4.2.6 on 2023-11-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_employeerresume_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerresume',
            name='profession',
            field=models.CharField(default='Программист', max_length=50),
            preserve_default=False,
        ),
    ]
