# Generated by Django 4.2.6 on 2023-11-04 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_workerresume_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerresume',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='employeerresume',
            name='profile_photo',
            field=models.ImageField(default='default_profile_photo.png', upload_to='images/%Y'),
        ),
        migrations.AlterField(
            model_name='workerresume',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='workerresume',
            name='profile_photo',
            field=models.ImageField(default='default_profile_photo.png', upload_to='images/%Y'),
        ),
    ]
