# Generated by Django 4.2.6 on 2023-11-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_employeerresume_owner_alter_workerresume_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerresume',
            name='description',
            field=models.TextField(default='Vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Enim nec dui nunc mattis. Pretium aenean pharetra magna ac. Duis tristique sollicitudin nibh sit amet. Sit amet porttitor eget dolor morbi non arcu. Quam id leo in vitae turpis massa. Massa id neque aliquam vestibulum morbi. Id ornare arcu odio ut sem nulla pharetra. Cras pulvinar mattis nunc sed blandit libero volutpat. Arcu ac tortor dignissim convallis. Ut faucibus pulvinar elementum integer enim neque. Sed nisi lacus sed viverra tellus in hac habitasse platea. Nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Non quam lacus suspendisse faucibus interdum posuere lorem. Curabitur vitae nunc sed velit dignissim sodales. Dui sapien eget mi proin sed libero enim sed faucibus. Eu consequat ac felis donec et odio pellentesque diam volutpat. Sed viverra tellus in hac. Nisl tincidunt eget nullam non nisi est sit. Feugiat vivamus at augue eget arcu dictum varius duis.', max_length=500),
            preserve_default=False,
        ),
    ]
